CREATE TABLE `user` (
  `id` varchar(255) NOT NULL,
  `name` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `update_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `recent_login_time` datetime DEFAULT NULL COMMENT '最近登录时间',
  `phone` varchar(11) DEFAULT NULL,
  `email` varchar(20) DEFAULT NULL,
  `concerns` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
)

-- 创建分类表 

CREATE TABLE category(
	id INT PRIMARY KEY AUTO_INCREMENT,
	category_name varchar(50) NOT NULL,
	creator varchar(50),
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

-- 创建文章
CREATE TABLE post(
	id varchar(50) NOT NULL,
	user_id varchar(50) NOT NULL,
	post_name  varchar(100) NOT NULL,
	post_title  varchar(100) NOT NULL,
	content TEXT  NOT NULL,
	category_ids  varchar(100),
	creator varchar(50),
	pv INT DEFAULT 0,
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
	FOREIGN KEY(category_id) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE
)

--  保存头像信息表
CREATE TABLE avatar (
	id INT PRIMARY KEY AUTO_INCREMENT,
	filename VARCHAR(255) NOT NULL UNIQUE,
	mimetype VARCHAR(30),
	size INT,
	user_id VARCHAR(50),
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) 

--  保存文件表
CREATE TABLE file (
	id INT PRIMARY KEY AUTO_INCREMENT,
	filename VARCHAR(255) NOT NULL UNIQUE,
	mimetype VARCHAR(30),
	size INT,
	user_id VARCHAR(50),
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) 

-- 创建评论表 
CREATE TABLE comment (
	id INT PRIMARY KEY AUTO_INCREMENT,
	post_id VARCHAR(50) NOT NULL,
	likes  INT DEFAULT 0,
	user_id VARCHAR(50) NOT NULL,
	content VARCHAR(255) NOT NULL COMMENT '评论内容',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
)

-- 创建评论回复表 
CREATE TABLE comment_reply (
	id INT PRIMARY KEY AUTO_INCREMENT,
	comment_id INT NOT NULL,
	post_id VARCHAR(50) NOT NULL,
	user_id VARCHAR(50) NOT NULL,
	likes  INT DEFAULT 0,
	to_uid VARCHAR(50) NOT NULL COMMENT '回复的目标用户id',
	content VARCHAR(255) NOT NULL COMMENT '评论内容',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (comment_id) REFERENCES comment(id) ON DELETE CASCADE ON UPDATE CASCADE
)

-- 创建收藏表 
CREATE TABLE collect (
	id INT PRIMARY KEY AUTO_INCREMENT,
	post_id VARCHAR(50) NOT NULL,
	user_id VARCHAR(50) NOT NULL,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
)




